permissions:
  contents: read
  pull-requests: read
on:
  push:
    branches:
      - wildcard
    paths:
      - "dist/github/**/*"

jobs:
  wildcard:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: |
          true
