permissions:
  contents: none
  pull-requests: none
on:
  push:
    branches:
      - wildcard
    paths:
      - "**/*.go"
      - ".golangci-version"
      - ".golangci.yml"
      - "go.*"
      - ".github/**"

jobs:
  wildcard:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: |
          true
