permissions:
  contents: none
  pull-requests: none
on:
  push:
    branches:
      - wildcard
    paths:
      - ".github/workflows/*.yml"
      - ".github/**"

jobs:
  wildcard:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: |
          true
