permissions:
  contents: none
  pull-requests: none
on:
  push:
    branches:
      - wildcard
    paths:
      - ".release/actions_env_mock.sh"
      - ".release/archive.sh"
      - "flake.nix"
      - "flake.lock"
jobs:
  wildcard:
    runs-on: ubuntu-latest
    steps:
      - run: |
          true
