permissions:
  contents: none
  pull-requests: none
on:
  push:
    branches:
      - wildcard
    paths:
      - "**/*.go"
      - ".golangci.yml"
      - "go.*"
      - "flake.nix"
      - "flake.lock"
jobs:
  wildcard:
    runs-on: ubuntu-latest
    steps:
      - run: |
          true
